In [1]:
import duckdb
import pandas as pd

In [2]:
sql_query = '''
show tables 
'''

with duckdb.connect('nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                             name
0  bronze_parking_violation_codes
1       bronze_parking_violations
2                     first_model
3         parking_violation_codes
4         parking_violations_2022
5                       ref_model
6  silver_parking_violation_codes
7       silver_parking_violations
8        silver_violation_tickets
9       silver_violation_vehicles

In [11]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT *
FROM read_csv_auto(
  'dof_parking_violation_codes.csv', max_line_size=10000000,
  normalize_names=True
  )
'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violations_2022 AS
SELECT *
FROM read_csv_auto(
  'Parking_Violations_Issued_Jeremy.csv', max_line_size=10000000,
  normalize_names=True
  )
'''

with duckdb.connect('nyc_parking_violations.db') as con:
  con.sql(sql_query_import_1)
  con.sql(sql_query_import_2)

In [5]:
sql_query = '''
SELECT * FROM gold_ticket_metrics
'''
with duckdb.connect('nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

    violation_code  ticket_count  total_revenue_usd
0               40            79             9085.0
1               98            68             6460.0
2               14            47             5405.0
3               46            42             4830.0
4               19            18             2070.0
5                6             3             1500.0
6               78            23             1495.0
7               17            13             1235.0
8               67             7             1155.0
9               20            14              840.0
10              51             6              690.0
11              48             5              575.0
12               7            11              550.0
13              74             8              520.0
14              70             8              520.0
15              21             6              390.0
16              50             3              345.0
17              71             5              325.0
18              99             3              315.0
19              24             4              240.0
20              16             2              190.0
21              27             1              180.0
22              18             1              115.0
23              53             1              115.0
24              56             1              115.0
25              31             1              115.0
26              83             1               65.0
27              39             1               60.0
28              68             1               60.0
29              62             1               45.0
30              66             1               45.0
31              80             1               45.0
32              91             1               45.0
33              38             1               35.0
34              41             4                0.0
35              94             1                NaN

In [6]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT *
FROM read_csv_auto(
  'dof_parking_violation_codes.csv', max_line_size=10000000,
  normalize_names=True
  )
'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violations_2022 AS
SELECT *
FROM read_csv_auto(
  'Parking_Violations_Issued_Jeremy.csv', max_line_size=10000000,
  normalize_names=True
  )
'''

with duckdb.connect('prod_nyc_parking_violations.db') as con:
  con.sql(sql_query_import_1)
  con.sql(sql_query_import_2)

In [7]:
sql_query = '''
show tables 
'''

with duckdb.connect('prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                             name
0  bronze_parking_violation_codes
1       bronze_parking_violations
2             gold_ticket_metrics
3            gold_vehicle_metrics
4         parking_violation_codes
5         parking_violations_2022
6        silver_violation_tickets
7       silver_violation_vehicles